# Generated by Django 4.1.7 on 2023-02-26 14:53

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='city',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='country',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adress',
            name='location',
            field=location_field.models.plain.PlainLocationField(default=1, max_length=63),
            preserve_default=False,
        ),
    ]
