# Generated by Django 4.1.7 on 2023-03-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adress_city_adress_country_adress_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
