# Generated by Django 4.1.7 on 2023-03-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_adress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
