# Generated by Django 4.1.7 on 2023-02-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_rating_shift_rename_drinks_drink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='store',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='store',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='store',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='food',
        ),
        migrations.AddField(
            model_name='drink',
            name='store',
            field=models.ManyToManyField(to='stores.store'),
        ),
        migrations.AddField(
            model_name='extra',
            name='store',
            field=models.ManyToManyField(to='stores.store'),
        ),
        migrations.AddField(
            model_name='rating',
            name='store',
            field=models.ManyToManyField(to='stores.store'),
        ),
        migrations.AddField(
            model_name='topping',
            name='food',
            field=models.ManyToManyField(to='stores.food'),
        ),
    ]
