# Generated by Django 4.1.7 on 2023-02-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_remove_drink_store_remove_extra_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='store',
        ),
        migrations.RemoveField(
            model_name='extra',
            name='store',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='store',
        ),
        migrations.AddField(
            model_name='drink',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extra',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
            preserve_default=False,
        ),
    ]
