# Generated by Django 4.1.7 on 2023-02-25 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_remove_drink_store_remove_extra_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('portion', models.CharField(max_length=36)),
                ('image', models.ImageField(upload_to='')),
                ('cuisine', models.CharField(max_length=36)),
                ('is_available', models.BooleanField()),
                ('vegan', models.BooleanField()),
                ('quantity', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.RemoveField(
            model_name='extra',
            name='store',
        ),
        migrations.RemoveField(
            model_name='food',
            name='store',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='food',
        ),
        migrations.DeleteModel(
            name='Drink',
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.itemcategory'),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
