# Generated by Django 4.1.7 on 2023-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_days_of_week_alter_rating_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='days_of_week',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rate',
            field=models.IntegerField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)]),
        ),
    ]
