# Generated by Django 4.1.7 on 2023-02-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_alter_rating_comment_delete_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cuisine',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
