# Generated by Django 4.1.7 on 2023-02-25 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_alter_store_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 17, 17, 46, 622231)),
        ),
    ]
