# Generated by Django 4.1.7 on 2023-02-25 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_item_portion_alter_rating_published_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 19, 1, 34, 788603)),
        ),
    ]
