# Generated by Django 4.1.7 on 2023-02-26 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('stores', '0017_alter_rating_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 15, 35, 9, 365885)),
        ),
    ]
