# Generated by Django 4.1.7 on 2023-02-26 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0023_alter_rating_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 26, 18, 53, 2, 508325)),
        ),
    ]
