# Generated by Django 4.1.7 on 2023-03-18 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0039_alter_rating_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 18, 17, 54, 21, 293961)),
        ),
    ]
