# Generated by Django 4.1.7 on 2023-03-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='test',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
    ]
