# Generated by Django 4.1.7 on 2023-03-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
